# Generated by Django 4.2 on 2025-04-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_loginattempt_is_blockedd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginattempt',
            name='is_blockedd',
        ),
    ]
