# Generated by Django 4.2 on 2025-04-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_loginattempt_is_blockedd'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
